### ISSUE TITLE
R3 Handsolder BOM

### ISSUE THREAD

**Issue by grasegger** [kilipan/miao#1]
Hi there,

I was wondering why R3 is missing in the bom for the hand solder version. The helios used a 600 ohm resistor for the same functionality, should the same be done for the miao?

**Comment by kilipan** [comment]
It's missing because the optimal part to put there depends a bit on your use-case. R3 connects shield and ground, which you sometimes can simply do with a 0 Ohm resistor, or you might want to leave entirely unconnected and let the USB host deal with shield, for example if you don't have a metallic shield to connect to.
